
-- ══════════════════════════════════════════════════════════════════
-- RESET COMPLET BASE DE DONNÉES — 2026-06-06
-- ══════════════════════════════════════════════════════════════════

-- Désactiver les contraintes FK temporairement
SET session_replication_role = replica;

-- Vider toutes les tables dans l'ordre inverse des FK
TRUNCATE sessions, results, standings, circuits, races, series RESTART IDENTITY CASCADE;

-- Réactiver les contraintes FK
SET session_replication_role = DEFAULT;

-- ── SERIES ──────────────────────────────────────────────────────
INSERT INTO series (id, name, color, icon) VALUES ('ELMS', 'European Le Mans Series', '#00e676', '🏁');
INSERT INTO series (id, name, color, icon) VALUES ('F1', 'Formula 1', '#e8001d', '🏎️');
INSERT INTO series (id, name, color, icon) VALUES ('GTWCE', 'GT World Challenge EU', '#b388ff', '🏆');
INSERT INTO series (id, name, color, icon) VALUES ('IMSA', 'IMSA WeatherTech', '#ff9500', '🇺🇸');
INSERT INTO series (id, name, color, icon) VALUES ('MotoGP', 'MotoGP', '#cc0099', '🏍️');
INSERT INTO series (id, name, color, icon) VALUES ('WEC', 'FIA WEC', '#00c8ff', '⏱️');
INSERT INTO series (id, name, color, icon) VALUES ('WRC', 'FIA World Rally Championship', '#1A1A1A', '🚗');

-- ── RACES ──────────────────────────────────────────────────────
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (1,'F1','GP Australie','Albert Park','Australie','2026-03-06','2026-03-08',1,'done','race','f1_albertpark');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (2,'F1','GP Chine','Shanghai International Circuit','Chine','2026-03-13','2026-03-15',2,'done','sprint_weekend','f1_shanghai');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (3,'F1','GP Japon','Suzuka International Racing Course','Japon','2026-03-27','2026-03-29',3,'done','race','f1_suzuka');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (4,'F1','GP Miami','Miami International Autodrome','États-Unis','2026-05-01','2026-05-03',4,'done','sprint_weekend','f1_miami');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (5,'F1','GP Canada','Circuit Gilles-Villeneuve','Canada','2026-05-22','2026-05-24',5,'done','sprint_weekend','f1_montreal');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (6,'F1','GP Monaco','Circuit de Monaco','Monaco','2026-06-05','2026-06-07',6,'upcoming','race','f1_monaco');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (7,'F1','GP Barcelone','Circuit de Barcelona-Catalunya','Espagne','2026-06-12','2026-06-14',7,'upcoming','race','f1_barcelona');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (8,'F1','GP Autriche','Red Bull Ring','Autriche','2026-06-26','2026-06-28',8,'upcoming','sprint_weekend','f1_redbullring');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (9,'F1','GP Grande-Bretagne','Silverstone Circuit','Angleterre','2026-07-03','2026-07-05',9,'upcoming','sprint_weekend','f1_silverstone');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (10,'F1','GP Belgique','Circuit de Spa-Francorchamps','Belgique','2026-07-17','2026-07-19',10,'upcoming','race','f1_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (11,'F1','GP Hongrie','Hungaroring','Hongrie','2026-07-24','2026-07-26',11,'upcoming','race','f1_hungaroring');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (12,'F1','GP Pays-Bas','Circuit Zandvoort','Pays-Bas','2026-08-21','2026-08-23',12,'upcoming','sprint_weekend','f1_zandvoort');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (13,'F1','GP Italie','Autodromo Nazionale Monza','Italie','2026-09-04','2026-09-06',13,'upcoming','race','f1_monza');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (14,'F1','GP Espagne Madrid','Madring','Espagne','2026-09-11','2026-09-13',14,'upcoming','race','f1_madrid');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (15,'F1','GP Azerbaïdjan','Baku City Circuit','Azerbaïdjan','2026-09-25','2026-09-27',15,'upcoming','race','f1_baku');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (16,'F1','GP Singapour','Marina Bay Street Circuit','Singapour','2026-10-09','2026-10-11',16,'upcoming','sprint_weekend','f1_marinabay');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (17,'F1','GP États-Unis','Circuit of the Americas','États-Unis','2026-10-23','2026-10-25',17,'upcoming','race','f1_cota');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (18,'F1','GP Mexique','Autodromo Hermanos Rodriguez','Mexique','2026-10-30','2026-11-01',18,'upcoming','race','f1_mexicocity');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (19,'F1','GP Brésil','Autodromo José Carlos Pace','Brésil','2026-11-06','2026-11-08',19,'upcoming','race','f1_interlagos');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (20,'F1','GP Las Vegas','Las Vegas Strip Circuit','États-Unis','2026-11-19','2026-11-21',20,'upcoming','race','f1_lasvegas');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (21,'F1','GP Qatar','Lusail International Circuit','Qatar','2026-11-27','2026-11-29',21,'upcoming','race','f1_losail');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (22,'F1','GP Abu Dhabi','Yas Marina Circuit','Abu Dhabi','2026-12-04','2026-12-06',22,'upcoming','race','f1_yasmarina');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (23,'MotoGP','GP Thaïlande','Chang International Circuit','Thaïlande','2026-02-27','2026-03-01',1,'done','sprint_weekend','motogp_tha');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (24,'MotoGP','GP Brésil','Autódromo Internacional Ayrton Senna','Brésil','2026-03-20','2026-03-22',2,'done','sprint_weekend','motogp_bra');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (25,'MotoGP','GP Amériques','Circuit of the Americas','États-Unis','2026-03-27','2026-03-29',3,'done','sprint_weekend','motogp_usa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (27,'MotoGP','GP Espagne','Circuito de Jerez','Espagne','2026-04-24','2026-04-26',4,'done','sprint_weekend','motogp_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (28,'MotoGP','GP France','Circuit Bugatti, Le Mans','France','2026-05-08','2026-05-10',5,'done','sprint_weekend','motogp_fra');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (29,'MotoGP','GP Catalogne','Circuit de Barcelona-Catalunya','Espagne','2026-05-15','2026-05-17',6,'done','sprint_weekend','motogp_cat');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (30,'MotoGP','GP Italie','Autodromo del Mugello','Italie','2026-05-29','2026-05-31',7,'done','sprint_weekend','motogp_ita');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (31,'MotoGP','GP Hongrie','Balaton Park Circuit','Hongrie','2026-06-05','2026-06-07',8,'upcoming','sprint_weekend','motogp_hun');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (32,'MotoGP','GP République Tchèque','Automotodrom Brno','Rep. Tcheque','2026-06-19','2026-06-21',9,'upcoming','sprint_weekend','motogp_cze');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (33,'MotoGP','GP Pays-Bas','TT Circuit Assen','Pays-Bas','2026-06-26','2026-06-28',10,'upcoming','sprint_weekend','motogp_nld');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (34,'MotoGP','GP Allemagne','Sachsenring','Allemagne','2026-07-10','2026-07-12',11,'upcoming','sprint_weekend','motogp_ger');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (35,'MotoGP','GP Grande-Bretagne','Silverstone Circuit','Angleterre','2026-08-07','2026-08-09',12,'upcoming','sprint_weekend','motogp_gbr');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (37,'MotoGP','GP Autriche','Red Bull Ring','Autriche','2026-09-18','2026-09-20',15,'upcoming','sprint_weekend','motogp_aut');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (38,'MotoGP','GP San Marin','Misano World Circuit','Italie','2026-09-11','2026-09-13',14,'upcoming','sprint_weekend','motogp_rsm');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (39,'MotoGP','GP Indonesie','Mandalika Circuit','Indonesie','2026-10-09','2026-10-11',17,'upcoming','sprint_weekend','motogp_ina');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (40,'MotoGP','GP Australie','Phillip Island Grand Prix Circuit','Australie','2026-10-23','2026-10-25',18,'upcoming','sprint_weekend','motogp_aus');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (41,'MotoGP','GP Malaisie','Sepang International Circuit','Malaisie','2026-10-30','2026-11-01',19,'upcoming','sprint_weekend','motogp_mal');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (44,'MotoGP','GP Valence','Circuit Ricardo Tormo','Espagne','2026-11-27','2026-11-29',22,'upcoming','sprint_weekend','motogp_val');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (45,'WEC','6H Imola','Autodromo Enzo e Dino Ferrari','Italie','2026-04-19','2026-04-19',1,'done','race','wec_imola');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (46,'WEC','6H Spa-Francorchamps','Circuit de Spa-Francorchamps','Belgique','2026-05-09','2026-05-09',2,'done','race','wec_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (47,'WEC','24H Le Mans','Circuit de la Sarthe','France','2026-06-13','2026-06-14',3,'upcoming','race','wec_lemans');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (48,'WEC','6H São Paulo','Autódromo José Carlos Pace','Brésil','2026-07-12','2026-07-12',4,'upcoming','race','wec_saopaulo');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (49,'WEC','6H Austin','Circuit of the Americas','États-Unis','2026-09-06','2026-09-06',5,'upcoming','race','wec_cota');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (50,'WEC','6H Fuji','Fuji International Speedway','Japon','2026-09-27','2026-09-27',6,'upcoming','race','wec_fuji');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (51,'WEC','Qatar 1812km','Lusail International Circuit','Qatar','2026-10-24','2026-10-24',7,'upcoming','race','wec_losail');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (52,'WEC','8H Bahreïn','Bahrain International Circuit','Bahreïn','2026-11-07','2026-11-07',8,'upcoming','race','wec_bahrain');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (53,'ELMS','4H Barcelone','Circuit de Barcelona-Catalunya','Espagne','2026-04-12','2026-04-12',1,'done','race','elms_barcelona');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (54,'ELMS','4H Paul Ricard','Circuit Paul Ricard','France','2026-05-03','2026-05-03',2,'done','race','elms_lecastellet');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (55,'ELMS','4H Imola','Autodromo Enzo e Dino Ferrari','Italie','2026-07-05','2026-07-05',3,'upcoming','race','elms_imola');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (56,'ELMS','4H Spa-Francorchamps','Circuit de Spa-Francorchamps','Belgique','2026-08-23','2026-08-23',4,'upcoming','race','elms_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (57,'ELMS','4H Silverstone','Silverstone Circuit','Angleterre','2026-09-13','2026-09-13',5,'upcoming','race','elms_silverstone');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (58,'ELMS','4H Portimão','Algarve International Circuit','Portugal','2026-10-10','2026-10-10',6,'upcoming','race','elms_portimao');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (59,'IMSA','Rolex 24 Daytona','Daytona International Speedway','États-Unis','2026-01-23','2026-01-25',1,'done','race','imsa_daytona');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (60,'IMSA','12H Sebring','Sebring International Raceway','États-Unis','2026-03-18','2026-03-21',2,'done','race','imsa_sebring');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (61,'IMSA','100 min Long Beach','Long Beach Street Circuit','États-Unis','2026-04-17','2026-04-19',3,'done','race','imsa_longbeach');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (62,'IMSA','2H40 Laguna Seca','WeatherTech Raceway Laguna Seca','États-Unis','2026-05-01','2026-05-03',4,'done','race','imsa_lagunaseca');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (63,'IMSA','100 min Detroit','Detroit Street Circuit','États-Unis','2026-05-29','2026-05-30',5,'done','race','imsa_detroit');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (64,'IMSA','6H Watkins Glen','Watkins Glen International','États-Unis','2026-06-25','2026-06-28',6,'upcoming','race','imsa_watkinsglen');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (65,'IMSA','2H40 Canadian Tire','Canadian Tire Motorsport Park','Canada','2026-07-10','2026-07-12',7,'upcoming','race','imsa_mosport');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (66,'IMSA','6H Road America','Road America','États-Unis','2026-07-30','2026-08-02',8,'upcoming','race','imsa_roadamerica');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (67,'IMSA','2H40 VIR','Virginia International Raceway','États-Unis','2026-08-20','2026-08-23',9,'upcoming','race','imsa_vir');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (68,'IMSA','Battle on the Bricks','Indianapolis Motor Speedway','États-Unis','2026-09-11','2026-09-13',10,'upcoming','race','imsa_indianapolis');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (69,'IMSA','Petit Le Mans','Road Atlanta','États-Unis','2026-10-01','2026-10-04',11,'upcoming','race','imsa_roadatlanta');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (70,'GTWCE','6H Paul Ricard','Circuit Paul Ricard','France','2026-04-11','2026-04-12',1,'done','race','gtwce_lecastellet');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (71,'GTWCE','24H Spa','Circuit de Spa-Francorchamps','Belgique','2026-06-25','2026-06-28',3,'upcoming','race','gtwce_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (72,'GTWCE','3H Nürburgring','Nürburgring','Allemagne','2026-07-26','2026-07-26',3,'upcoming','race','gtwce_nurburgring');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (74,'GTWCE','3H Portimão','Algarve International Circuit','Portugal','2026-10-18','2026-10-18',5,'upcoming','race','gtwce_portimao');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (75,'F1','Sprint — Chine','Shanghai International Circuit','Chine','2026-03-14','2026-03-14',2,'done','sprint','f1_shanghai');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (76,'F1','Sprint — Miami','Miami International Autodrome','États-Unis','2026-05-02','2026-05-02',4,'done','sprint','f1_miami');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (77,'F1','Sprint — Canada','Circuit Gilles-Villeneuve','Canada','2026-05-23','2026-05-23',5,'done','sprint','f1_montreal');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (78,'F1','Sprint — Grande-Bretagne','Silverstone Circuit','Angleterre','2026-07-04','2026-07-04',9,'upcoming','sprint','f1_silverstone');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (79,'F1','Sprint — Pays-Bas','Circuit Zandvoort','Pays-Bas','2026-08-22','2026-08-22',12,'upcoming','sprint','f1_zandvoort');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (80,'F1','Sprint — Singapour','Marina Bay Street Circuit','Singapour','2026-10-10','2026-10-10',16,'upcoming','sprint','f1_marinabay');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (81,'MotoGP','Sprint — Thaïlande','Chang International Circuit','Thaïlande','2026-03-01','2026-03-01',1,'done','sprint','motogp_tha');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (82,'MotoGP','Sprint — Brésil','Autódromo Internacional Ayrton Senna','Brésil','2026-03-22','2026-03-22',2,'done','sprint','motogp_bra');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (83,'MotoGP','Sprint — Amériques','Circuit of the Americas','États-Unis','2026-03-29','2026-03-29',3,'done','sprint','motogp_usa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (85,'MotoGP','Sprint — France','Circuito de Jerez','Espagne','2026-04-24','2026-04-26',5,'done','sprint','motogp_fra');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (86,'MotoGP','Sprint — Catalogne','Circuit Bugatti, Le Mans','France','2026-05-10','2026-05-10',6,'done','sprint','motogp_cat');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (87,'MotoGP','Sprint — Italie','Circuit de Barcelona-Catalunya','Espagne','2026-05-17','2026-05-17',7,'done','sprint','motogp_ita');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (88,'GTWCE','3H Monza','Autodromo Nazionale Monza','Italie','2026-05-30','2026-05-31',2,'done','race','gtwce_monza');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (104,'MotoGP','GP Japon','Motegi Circuit','Japon','2026-10-02','2026-10-04',16,'upcoming','sprint_weekend','motogp_jpn');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (119,'MotoGP','Sprint - Hongrie','Balaton Park Circuit','Hongrie','2026-06-05','2026-06-07',8,'upcoming','sprint','motogp_hun');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (120,'MotoGP','Sprint - République Tchèque','Automotodrom Brno','Rep. Tcheque','2026-06-19','2026-06-21',9,'upcoming','sprint','motogp_cze');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (121,'MotoGP','Sprint - Pays-Bas','TT Circuit Assen','Pays-Bas','2026-06-26','2026-06-28',10,'upcoming','sprint','motogp_nld');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (122,'MotoGP','Sprint - Allemagne','Sachsenring','Allemagne','2026-07-10','2026-07-12',11,'upcoming','sprint','motogp_ger');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (123,'MotoGP','Sprint - Grande-Bretagne','Silverstone Circuit','Angleterre','2026-08-07','2026-08-09',12,'upcoming','sprint','motogp_gbr');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (125,'MotoGP','Sprint - Autriche','Red Bull Ring','Autriche','2026-09-18','2026-09-20',15,'upcoming','sprint','motogp_aut');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (126,'MotoGP','Sprint - Indonesie','Mandalika Circuit','Indonesie','2026-10-09','2026-10-11',17,'upcoming','sprint','motogp_ina');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (127,'MotoGP','Sprint - Qatar','Lusail International Circuit','Qatar','2026-11-06','2026-11-08',20,'upcoming','sprint','motogp_qat');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (128,'MotoGP','Sprint - Japon','Motegi Circuit','Japon','2026-10-02','2026-10-04',16,'upcoming','sprint','motogp_jpn');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (129,'MotoGP','Sprint - San Marin','Misano World Circuit','Italie','2026-09-11','2026-09-13',14,'upcoming','sprint','motogp_rsm');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (130,'MotoGP','Sprint - Australie','Phillip Island Grand Prix Circuit','Australie','2026-10-23','2026-10-25',18,'upcoming','sprint','motogp_aus');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (131,'MotoGP','Sprint - Malaisie','Sepang International Circuit','Malaisie','2026-10-30','2026-11-01',19,'upcoming','sprint','motogp_mal');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (132,'MotoGP','Sprint - Valence','Circuit Ricardo Tormo','Espagne','2026-11-27','2026-11-29',22,'upcoming','sprint','motogp_val');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (133,'MotoGP','GP Aragon','MotorLand Aragon','Espagne','2026-08-28','2026-08-30',13,'upcoming','sprint_weekend','motogp_ara');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (134,'MotoGP','Sprint - Aragon','MotorLand Aragon','Espagne','2026-08-28','2026-08-30',13,'upcoming','sprint','motogp_ara');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (135,'MotoGP','GP Portugal','Algarve International Circuit','Portugal','2026-11-20','2026-11-22',21,'upcoming','sprint_weekend','motogp_por');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (136,'MotoGP','Sprint - Portugal','Algarve International Circuit','Portugal','2026-11-20','2026-11-22',21,'upcoming','sprint','motogp_por');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (137,'MotoGP','Sprint - Espagne','Circuito de Jerez','Espagne','2026-04-24','2026-04-26',4,'done','sprint','motogp_spa');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (138,'MotoGP','GP Qatar','Lusail International Circuit','Qatar','2026-11-06','2026-11-08',20,'upcoming','sprint_weekend','motogp_qat');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (153,'WRC','Rallye Monte-Carlo','Monaco','Monaco','2026-01-22','2026-01-25',1,'done','race','wrc_montecarlo');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (154,'WRC','Rally Sweden','Umea','Suede','2026-02-12','2026-02-15',2,'done','race','wrc_sweden');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (155,'WRC','Safari Rally Kenya','Naivasha','Kenya','2026-03-12','2026-03-15',3,'done','race','wrc_kenya');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (156,'WRC','Croatia Rally','Rijeka','Croatie','2026-04-09','2026-04-12',4,'done','race','wrc_croatia');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (157,'WRC','Rally Islas Canarias','Las Palmas','Espagne','2026-04-23','2026-04-26',5,'done','race','wrc_canarias');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (158,'WRC','Rally de Portugal','Matosinhos','Portugal','2026-05-07','2026-05-10',6,'done','race','wrc_portugal');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (159,'WRC','Rally Japan','Toyota','Japon','2026-05-28','2026-05-31',7,'done','race','wrc_japan');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (160,'WRC','EKO Acropolis Rally Greece','Lamia','Grece','2026-06-25','2026-06-28',8,'upcoming','race','wrc_greece');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (161,'WRC','Rally Estonia','Tartu','Estonie','2026-07-16','2026-07-19',9,'upcoming','race','wrc_estonia');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (162,'WRC','Rally Finland','Jyvaskyla','Finlande','2026-07-30','2026-08-02',10,'upcoming','race','wrc_finland');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (163,'WRC','Rally Paraguay','Asuncion','Paraguay','2026-08-27','2026-08-30',11,'upcoming','race','wrc_paraguay');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (164,'WRC','Rally Chile','Santiago','Chili','2026-09-10','2026-09-13',12,'upcoming','race','wrc_chile');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (165,'WRC','Rally Italy','Italie','Italie','2026-10-01','2026-10-04',13,'upcoming','race','wrc_italy');
INSERT INTO races (id,series_id,name,circuit,country,date_start,date_end,round,status,type,circuit_key) VALUES (166,'WRC','Rally Saudi Arabia','Arabie Saoudite','Arabie Saoudite','2026-11-12','2026-11-15',14,'upcoming','race','wrc_saudi');

SELECT setval('races_id_seq', 166);